services:
  php:
    build: .
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./public:/var/www/html
    links:
      - db
  db:
    image: mysql:8
    ports:
      - "3307:3306"
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_DATABASE=db_app_db2
      - MYSQL_ROOT_PASSWORD=123456